<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Jellyfin.Plugin.Watchlist</RootNamespace>
    <AssemblyName>Jellyfin.Plugin.Watchlist</AssemblyName>
    <Version>1.1.0.0</Version>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="12.0.0" />
    <PackageReference Include="Jellyfin.Model" Version="12.0.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration\**" />
    <EmbeddedResource Include="Pages\**" />
    <EmbeddedResource Include="Web\**" />
  </ItemGroup>

</Project>
